In [1]:
import policies
import scenarios
import torch as pt
import numpy as np

def sample_initial_dist():
    return np.random.normal(2.5, 0.1)

def sample_sensor_noise(cov):
    return np.random.normal(0, np.sqrt(cov))

scenario = scenarios.LavaScenario(sample_initial_dist, lambda: sample_sensor_noise(0.001))

In [2]:
np.random.seed(0)
pt.manual_seed(0)

#policy = policies.PGPolicy(scenario, 10, [64, 32], 0.1 * np.eye(scenario.ninputs))
#policy.train(nsamples=1000, training_iterations=200)

ntrvs = 2

policy = policies.MINEPolicy(scenario, 5, ntrvs, [256], 0.1 * np.eye(ntrvs), [256], 0.1 * np.eye(scenario.ninputs), 0.01, {'hidden_size' : 100})
policy.train(nsamples=500, training_iterations=500, qlr=0.0001, pilr=0.0001)

[0]		Avg. Cost: 1067.340		Est. MI: 0.000		Total: 1067.343
[1]		Avg. Cost: 1058.098		Est. MI: 0.004		Total: 1058.451
[2]		Avg. Cost: 986.815		Est. MI: 0.003		Total: 987.161
[3]		Avg. Cost: 1001.315		Est. MI: 0.004		Total: 1001.678
[4]		Avg. Cost: 1002.122		Est. MI: 0.005		Total: 1002.649
[5]		Avg. Cost: 970.784		Est. MI: 0.005		Total: 971.281
[6]		Avg. Cost: 908.033		Est. MI: 0.005		Total: 908.551
[7]		Avg. Cost: 909.035		Est. MI: 0.006		Total: 909.597
[8]		Avg. Cost: 989.216		Est. MI: 0.005		Total: 989.747
[9]		Avg. Cost: 946.835		Est. MI: 0.005		Total: 947.359
[10]		Avg. Cost: 969.451		Est. MI: 0.006		Total: 970.062
[11]		Avg. Cost: 949.118		Est. MI: 0.007		Total: 949.846
[12]		Avg. Cost: 894.947		Est. MI: 0.006		Total: 895.545
[13]		Avg. Cost: 943.357		Est. MI: 0.006		Total: 943.960
[14]		Avg. Cost: 893.260		Est. MI: 0.006		Total: 893.858
[15]		Avg. Cost: 945.882		Est. MI: 0.006		Total: 946.476
[16]		Avg. Cost: 948.362		Est. MI: 0.006		Total: 948.971
[17]		Avg. Cost: 793.946		Est. MI

[143]		Avg. Cost: 856.409		Est. MI: 0.007		Total: 857.069
[144]		Avg. Cost: 851.620		Est. MI: 0.006		Total: 852.217
[145]		Avg. Cost: 855.800		Est. MI: 0.007		Total: 856.491
[146]		Avg. Cost: 903.267		Est. MI: 0.006		Total: 903.862
[147]		Avg. Cost: 883.425		Est. MI: 0.007		Total: 884.078
[148]		Avg. Cost: 802.485		Est. MI: 0.006		Total: 803.117
[149]		Avg. Cost: 812.759		Est. MI: 0.006		Total: 813.324
[150]		Avg. Cost: 880.512		Est. MI: 0.007		Total: 881.239
[151]		Avg. Cost: 891.670		Est. MI: 0.005		Total: 892.180
[152]		Avg. Cost: 877.937		Est. MI: 0.007		Total: 878.591
[153]		Avg. Cost: 837.106		Est. MI: 0.007		Total: 837.766
[154]		Avg. Cost: 888.614		Est. MI: 0.005		Total: 889.146
[155]		Avg. Cost: 769.356		Est. MI: 0.008		Total: 770.163
[156]		Avg. Cost: 938.882		Est. MI: 0.007		Total: 939.597
[157]		Avg. Cost: 880.059		Est. MI: 0.007		Total: 880.753
[158]		Avg. Cost: 924.172		Est. MI: 0.007		Total: 924.901
[159]		Avg. Cost: 901.167		Est. MI: 0.006		Total: 901.724
[160]		Avg. Co

[285]		Avg. Cost: 828.202		Est. MI: 0.008		Total: 829.013
[286]		Avg. Cost: 751.837		Est. MI: 0.007		Total: 752.575
[287]		Avg. Cost: 805.561		Est. MI: 0.008		Total: 806.356
[288]		Avg. Cost: 799.612		Est. MI: 0.008		Total: 800.443
[289]		Avg. Cost: 716.376		Est. MI: 0.008		Total: 717.158
[290]		Avg. Cost: 773.524		Est. MI: 0.010		Total: 774.476
[291]		Avg. Cost: 645.415		Est. MI: 0.008		Total: 646.228
[292]		Avg. Cost: 740.127		Est. MI: 0.007		Total: 740.871
[293]		Avg. Cost: 688.833		Est. MI: 0.008		Total: 689.584
[294]		Avg. Cost: 790.865		Est. MI: 0.008		Total: 791.681
[295]		Avg. Cost: 763.578		Est. MI: 0.008		Total: 764.401
[296]		Avg. Cost: 815.397		Est. MI: 0.007		Total: 816.048
[297]		Avg. Cost: 717.410		Est. MI: 0.007		Total: 718.156
[298]		Avg. Cost: 837.377		Est. MI: 0.010		Total: 838.393
[299]		Avg. Cost: 811.702		Est. MI: 0.009		Total: 812.644
[300]		Avg. Cost: 732.003		Est. MI: 0.008		Total: 732.796
[301]		Avg. Cost: 671.342		Est. MI: 0.006		Total: 671.968
[302]		Avg. Co

[427]		Avg. Cost: 664.830		Est. MI: 0.008		Total: 665.636
[428]		Avg. Cost: 632.830		Est. MI: 0.009		Total: 633.748
[429]		Avg. Cost: 576.818		Est. MI: 0.009		Total: 577.721
[430]		Avg. Cost: 672.767		Est. MI: 0.010		Total: 673.761
[431]		Avg. Cost: 620.341		Est. MI: 0.009		Total: 621.204
[432]		Avg. Cost: 627.552		Est. MI: 0.008		Total: 628.373
[433]		Avg. Cost: 687.777		Est. MI: 0.011		Total: 688.847
[434]		Avg. Cost: 656.026		Est. MI: 0.010		Total: 657.002
[435]		Avg. Cost: 651.586		Est. MI: 0.010		Total: 652.567
[436]		Avg. Cost: 640.238		Est. MI: 0.010		Total: 641.193
[437]		Avg. Cost: 562.843		Est. MI: 0.010		Total: 563.795
[438]		Avg. Cost: 562.747		Est. MI: 0.010		Total: 563.743
[439]		Avg. Cost: 695.406		Est. MI: 0.009		Total: 696.262
[440]		Avg. Cost: 610.836		Est. MI: 0.009		Total: 611.777
[441]		Avg. Cost: 597.071		Est. MI: 0.010		Total: 598.036
[442]		Avg. Cost: 770.069		Est. MI: 0.011		Total: 771.160
[443]		Avg. Cost: 590.092		Est. MI: 0.009		Total: 590.988
[444]		Avg. Co

In [11]:
def test_sample_initial_dist():
    return np.random.normal(2.5, 0.01)

def test_sample_sensor_noise(cov):
    return np.random.normal(0, np.sqrt(cov))

test_scenario = scenarios.LavaScenario(test_sample_initial_dist, lambda: test_sample_sensor_noise(1))

policy._scenario = test_scenario

states, outputs, trvs, inputs, costs = policy.rollout(10000)

costs.sum(axis=0).mean()

892.8651843504626

In [9]:
def test_sample_initial_dist():
    return np.random.uniform(0, 5)

def test_sample_sensor_noise(cov):
    return np.random.normal(0, np.sqrt(cov))

test_scenario = scenarios.LavaScenario(test_sample_initial_dist, lambda: test_sample_sensor_noise(0.001))

policy._scenario = test_scenario

policy.rollout(10000)[4].sum(axis=0).mean()

1824.579745695017

In [13]:
inputs.mean(axis=2)

array([[ 0.11715262, -0.07309005, -0.4447795 ,  0.28603853,  0.19557988]])

In [15]:
states.mean(axis=2)

array([[ 2.49988937,  2.49988937,  2.61704199,  2.66116275,  2.27216295,
         2.2012928 ],
       [ 0.        ,  0.11715262,  0.04406257, -0.40115026, -0.11265001,
         0.08133341]])

In [20]:
states[:, :, 75]

array([[ 2.50249575,  2.50249575,  2.46911727,  2.59771304,  3.30487846,
         3.82222651],
       [ 0.        , -0.03337848,  0.12859577,  0.70716542,  0.51734805,
         0.51872334]])