In [1]:
import policies
import scenarios
import torch as pt
import numpy as np

def sample_initial_dist():
    return np.random.uniform(0, 5)

def sample_sensor_noise(cov):
    return np.random.normal(0, np.sqrt(cov))

scenario = scenarios.LavaScenario(sample_initial_dist, lambda: sample_sensor_noise(0.001))

In [9]:
np.random.seed(0)
pt.manual_seed(0)

#policy = policies.PGPolicy(scenario, 10, [64, 32], 0.1 * np.eye(scenario.ninputs))
#policy.train(nsamples=1000, training_iterations=200)

ntrvs = 2

policy = policies.MINEPolicy(scenario, 5, ntrvs, [256], 0.1 * np.eye(ntrvs), [256], 0.1 * np.eye(scenario.ninputs), 0.01, {'hidden_size' : 100})
policy.train(nsamples=500, training_iterations=700, qlr=0.0001, pilr=0.0001)

[0]		Avg. Cost: 2238.648		Est. MI: 0.021		Total: 2240.736
[1]		Avg. Cost: 1926.498		Est. MI: 0.025		Total: 1928.977
[2]		Avg. Cost: 2109.055		Est. MI: 0.023		Total: 2111.398
[3]		Avg. Cost: 2098.477		Est. MI: 0.023		Total: 2100.779
[4]		Avg. Cost: 1956.375		Est. MI: 0.021		Total: 1958.495
[5]		Avg. Cost: 1901.693		Est. MI: 0.021		Total: 1903.835
[6]		Avg. Cost: 1668.161		Est. MI: 0.022		Total: 1670.391
[7]		Avg. Cost: 1620.565		Est. MI: 0.021		Total: 1622.692
[8]		Avg. Cost: 1852.237		Est. MI: 0.020		Total: 1854.223
[9]		Avg. Cost: 1768.200		Est. MI: 0.023		Total: 1770.460
[10]		Avg. Cost: 1656.789		Est. MI: 0.022		Total: 1659.003
[11]		Avg. Cost: 1739.306		Est. MI: 0.022		Total: 1741.534
[12]		Avg. Cost: 1597.949		Est. MI: 0.023		Total: 1600.234
[13]		Avg. Cost: 1859.828		Est. MI: 0.021		Total: 1861.916
[14]		Avg. Cost: 1711.303		Est. MI: 0.022		Total: 1713.515
[15]		Avg. Cost: 1710.510		Est. MI: 0.022		Total: 1712.687
[16]		Avg. Cost: 1630.558		Est. MI: 0.023		Total: 1632.874
[17]		A

[139]		Avg. Cost: 1140.955		Est. MI: 0.025		Total: 1143.421
[140]		Avg. Cost: 1084.616		Est. MI: 0.023		Total: 1086.871
[141]		Avg. Cost: 1057.849		Est. MI: 0.023		Total: 1060.149
[142]		Avg. Cost: 1083.929		Est. MI: 0.023		Total: 1086.248
[143]		Avg. Cost: 1114.975		Est. MI: 0.023		Total: 1117.257
[144]		Avg. Cost: 1132.768		Est. MI: 0.024		Total: 1135.163
[145]		Avg. Cost: 1020.990		Est. MI: 0.021		Total: 1023.052
[146]		Avg. Cost: 1106.421		Est. MI: 0.024		Total: 1108.811
[147]		Avg. Cost: 1083.467		Est. MI: 0.024		Total: 1085.828
[148]		Avg. Cost: 1039.197		Est. MI: 0.021		Total: 1041.307
[149]		Avg. Cost: 1024.997		Est. MI: 0.020		Total: 1026.990
[150]		Avg. Cost: 1173.563		Est. MI: 0.025		Total: 1176.022
[151]		Avg. Cost: 1099.552		Est. MI: 0.022		Total: 1101.742
[152]		Avg. Cost: 1111.048		Est. MI: 0.022		Total: 1113.297
[153]		Avg. Cost: 1132.949		Est. MI: 0.023		Total: 1135.275
[154]		Avg. Cost: 1154.220		Est. MI: 0.023		Total: 1156.540
[155]		Avg. Cost: 968.989		Est. MI: 0.02

[277]		Avg. Cost: 1082.466		Est. MI: 0.027		Total: 1085.155
[278]		Avg. Cost: 940.686		Est. MI: 0.026		Total: 943.270
[279]		Avg. Cost: 1145.599		Est. MI: 0.030		Total: 1148.573
[280]		Avg. Cost: 917.549		Est. MI: 0.026		Total: 920.191
[281]		Avg. Cost: 1027.030		Est. MI: 0.027		Total: 1029.733
[282]		Avg. Cost: 1222.258		Est. MI: 0.027		Total: 1224.964
[283]		Avg. Cost: 1056.747		Est. MI: 0.027		Total: 1059.446
[284]		Avg. Cost: 1131.400		Est. MI: 0.027		Total: 1134.101
[285]		Avg. Cost: 1078.300		Est. MI: 0.027		Total: 1080.989
[286]		Avg. Cost: 991.911		Est. MI: 0.027		Total: 994.599
[287]		Avg. Cost: 1085.612		Est. MI: 0.026		Total: 1088.231
[288]		Avg. Cost: 1095.072		Est. MI: 0.028		Total: 1097.906
[289]		Avg. Cost: 1003.274		Est. MI: 0.027		Total: 1005.956
[290]		Avg. Cost: 1023.014		Est. MI: 0.027		Total: 1025.736
[291]		Avg. Cost: 949.727		Est. MI: 0.027		Total: 952.450
[292]		Avg. Cost: 1031.264		Est. MI: 0.029		Total: 1034.167
[293]		Avg. Cost: 968.486		Est. MI: 0.029		Total

[416]		Avg. Cost: 1055.432		Est. MI: 0.030		Total: 1058.474
[417]		Avg. Cost: 1033.285		Est. MI: 0.032		Total: 1036.436
[418]		Avg. Cost: 1059.454		Est. MI: 0.032		Total: 1062.697
[419]		Avg. Cost: 896.498		Est. MI: 0.032		Total: 899.652
[420]		Avg. Cost: 1036.246		Est. MI: 0.028		Total: 1039.066
[421]		Avg. Cost: 957.265		Est. MI: 0.030		Total: 960.267
[422]		Avg. Cost: 953.146		Est. MI: 0.030		Total: 956.167
[423]		Avg. Cost: 999.088		Est. MI: 0.035		Total: 1002.611
[424]		Avg. Cost: 1010.986		Est. MI: 0.034		Total: 1014.347
[425]		Avg. Cost: 907.229		Est. MI: 0.031		Total: 910.353
[426]		Avg. Cost: 953.141		Est. MI: 0.032		Total: 956.346
[427]		Avg. Cost: 929.701		Est. MI: 0.029		Total: 932.604
[428]		Avg. Cost: 897.165		Est. MI: 0.031		Total: 900.256
[429]		Avg. Cost: 953.806		Est. MI: 0.029		Total: 956.706
[430]		Avg. Cost: 999.756		Est. MI: 0.033		Total: 1003.082
[431]		Avg. Cost: 940.085		Est. MI: 0.031		Total: 943.228
[432]		Avg. Cost: 996.916		Est. MI: 0.034		Total: 1000.329
[

[557]		Avg. Cost: 927.116		Est. MI: 0.032		Total: 930.266
[558]		Avg. Cost: 959.141		Est. MI: 0.034		Total: 962.526
[559]		Avg. Cost: 865.268		Est. MI: 0.035		Total: 868.798
[560]		Avg. Cost: 964.992		Est. MI: 0.035		Total: 968.460
[561]		Avg. Cost: 869.986		Est. MI: 0.037		Total: 873.674
[562]		Avg. Cost: 813.987		Est. MI: 0.034		Total: 817.415
[563]		Avg. Cost: 960.241		Est. MI: 0.035		Total: 963.775
[564]		Avg. Cost: 963.989		Est. MI: 0.032		Total: 967.175
[565]		Avg. Cost: 843.886		Est. MI: 0.036		Total: 847.453
[566]		Avg. Cost: 816.004		Est. MI: 0.036		Total: 819.558
[567]		Avg. Cost: 831.772		Est. MI: 0.033		Total: 835.089
[568]		Avg. Cost: 891.882		Est. MI: 0.036		Total: 895.519
[569]		Avg. Cost: 841.203		Est. MI: 0.036		Total: 844.844
[570]		Avg. Cost: 877.807		Est. MI: 0.034		Total: 881.180
[571]		Avg. Cost: 1004.468		Est. MI: 0.034		Total: 1007.842
[572]		Avg. Cost: 881.219		Est. MI: 0.033		Total: 884.487
[573]		Avg. Cost: 816.718		Est. MI: 0.033		Total: 820.044
[574]		Avg. 

[699]		Avg. Cost: 763.513		Est. MI: 0.042		Total: 767.695


In [16]:
def test_sample_initial_dist():
    return np.random.normal(2.5, 0.01)

def test_sample_sensor_noise(cov):
    return np.random.normal(0, np.sqrt(cov))

test_scenario = scenarios.LavaScenario(test_sample_initial_dist, lambda: test_sample_sensor_noise(1))

policy._scenario = test_scenario

states, outputs, trvs, inputs, costs = policy.rollout(10000)

costs.sum(axis=0).mean()

1057.7469538686823

In [26]:
def test_sample_initial_dist():
    return np.random.uniform(0, 5)

def test_sample_sensor_noise(cov):
    return np.random.normal(0, np.sqrt(cov))

test_scenario = scenarios.LavaScenario(test_sample_initial_dist, lambda: test_sample_sensor_noise(3))

policy._scenario = test_scenario

states, outputs, trvs, inputs, costs = policy.rollout(10000)

costs.sum(axis=0).mean()

1765.5806621213414

In [22]:
inputs.mean(axis=2)

array([[-0.41322709,  0.20504078, -0.07300997,  0.66933487, -0.27360977]])

In [18]:
states.mean(axis=2)[0, :]

array([2.50012542, 2.50012542, 2.06783774, 1.85879211, 1.64516854,
       2.09981579])

In [24]:
inputs.mean(axis=2)

array([[-0.41467385,  0.19477531, -0.08138459,  0.68341339, -0.26450963]])

In [27]:
inputs.mean(axis=2)

array([[-0.42243527,  0.17748294, -0.10133495,  0.69073551, -0.26920205]])