In [26]:
import policies
import scenarios
import torch as pt
import numpy as np

def sample_initial_dist():
    return np.random.uniform(0, 5)#np.random.normal(2.5, 0.1)

def sample_sensor_noise(cov):
    return np.random.normal(0, np.sqrt(cov))

scenario = scenarios.LavaScenario(sample_initial_dist, lambda: sample_sensor_noise(0.001))

In [27]:
np.random.seed(0)
pt.manual_seed(0)

#policy = policies.PGPolicy(scenario, 5, 500, [256, 256], 0.1 * np.eye(scenario.ninputs))
#policy.train(training_iterations=200, lr=0.001)

ntrvs = 5

policy = policies.MINEPolicy(scenario, 5, 500, ntrvs, [256], 0.1 * np.eye(ntrvs), [256], 0.1 * np.eye(scenario.ninputs), 100, {'hidden_size' : 100})
policy.train(nsamples=1000, training_iterations=100, qlr=0.001, pilr=0.001)

[0]		Avg. Cost: 2651.317		Est. MI: 1.319		Total: 2783.204
[1]		Avg. Cost: 1525.990		Est. MI: 1.112		Total: 1637.187
[2]		Avg. Cost: 1646.848		Est. MI: 0.573		Total: 1704.130
[3]		Avg. Cost: 1416.540		Est. MI: 0.241		Total: 1440.661
[4]		Avg. Cost: 1571.108		Est. MI: 0.206		Total: 1591.677
[5]		Avg. Cost: 1580.131		Est. MI: 0.214		Total: 1601.522
[6]		Avg. Cost: 1444.158		Est. MI: 0.355		Total: 1479.705
[7]		Avg. Cost: 1467.871		Est. MI: 0.434		Total: 1511.222
[8]		Avg. Cost: 1496.824		Est. MI: 0.448		Total: 1541.601
[9]		Avg. Cost: 1528.606		Est. MI: 0.241		Total: 1552.734
[10]		Avg. Cost: 1543.290		Est. MI: 0.213		Total: 1564.581
[11]		Avg. Cost: 1499.427		Est. MI: 0.181		Total: 1517.532
[12]		Avg. Cost: 1571.526		Est. MI: 0.210		Total: 1592.531
[13]		Avg. Cost: 1541.713		Est. MI: 0.281		Total: 1569.786
[14]		Avg. Cost: 1476.835		Est. MI: 0.203		Total: 1497.184
[15]		Avg. Cost: 1499.257		Est. MI: 0.210		Total: 1520.215
[16]		Avg. Cost: 1439.546		Est. MI: 0.211		Total: 1460.612
[17]		A

In [28]:
def test_sample_initial_dist():
    return np.random.normal(2.5, 0.1)

def test_sample_sensor_noise(cov):
    return np.random.normal(0, np.sqrt(cov))

test_scenario = scenarios.LavaScenario(test_sample_initial_dist, lambda: test_sample_sensor_noise(1))

policy._scenario = test_scenario

states, outputs, trvs, inputs, costs = policy.rollout(500)
costs[0, :, :].sum(axis=0).mean().item()

1165.2705078125

In [33]:
def test_sample_initial_dist():
    return np.random.uniform(3, 5)

def test_sample_sensor_noise(cov):
    return np.random.normal(0, np.sqrt(cov))

test_scenario = scenarios.LavaScenario(test_sample_initial_dist, lambda: test_sample_sensor_noise(1))

policy._scenario = test_scenario

states, outputs, trvs, inputs, costs = policy.rollout(500)
costs[0, :, :].sum(axis=0).mean().item()

1087.02978515625

In [ ]:
inputs.mean(axis=2)

In [4]:
a = pt.zeros((3, 4, 2))

1114.52587890625

In [14]:
costs.shape

torch.Size([1, 6, 500])

In [ ]:
a[:, 1, :]

In [ ]:
b

In [ ]:
policy._states[:, 0, :]

In [ ]:
a = pt.zeros(3)

In [ ]:
b = a

In [ ]:
b[0] = 3
a

In [15]:
a = pt.tensor([1.0, 5.0, 6.0, 23.0], requires_grad=True)

In [16]:
b = a **2

In [7]:
b.grad

In [17]:
c = b.sum()

In [18]:
c.backward()

In [19]:
print(a.grad)

tensor([ 2., 10., 12., 46.])


In [25]:
c.requires_grad = True
d = c / 2

In [3]:
d

NameError: name 'd' is not defined

In [10]:
b.sum()

tensor(591., grad_fn=<SumBackward0>)

In [11]:
c = pt.zeros(3)

In [12]:
c[1] = b.sum()

In [15]:
c.sum()

tensor(591., grad_fn=<SumBackward0>)

In [5]:
a.grad

In [6]:
a

tensor([ 1.,  5.,  6., 23.], requires_grad=True)

In [14]:
x = pt.tensor([[1., -1.], [1., 1.]], requires_grad=True)
out = x.pow(2).sum()
out.backward()
x.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])